### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by achilleas-kr** [pyansys/pyfluent#1097]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I use python 3.9.11.
I use Fluent v23R1.
I use pyFluent 0.12.dev3.
I use visualisation & parametric packages 0.6.dev0.

I am not able to run the example from github, located here https://github.com/pyansys/pyfluent-visualization/blob/main/examples/00-postprocessing/post_processing_exhaust_manifold.py

I am getting an error I cannot fix. Error is posted below:

Traceback (most recent call last):
  File "C:\Users\akrikas\UnSync\PyAnsys\Learning\script.py", line 83, in <module>
    mesh1.display("window-1")
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\pyvista\pyvista_objects.py", line 142, in display
    pyvista_windows_manager.plot(self, window_id)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\pyvista\pyvista_windows_manager.py", line 451, in plot
    self._plot_notebook(object, window_id)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\pyvista\pyvista_windows_manager.py", line 624, in _plot_notebook
    window.plot()
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\pyvista\pyvista_windows_manager.py", line 60, in plot
    self._display_mesh(obj, plotter)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\pyvista\pyvista_windows_manager.py", line 316, in _display_mesh
    surfaces_data = FieldDataExtractor(obj).fetch_data()
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\post_data_extractor.py", line 39, in fetch_data
    return self._fetch_mesh_data(self._post_object, *args, **kwargs)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\post_data_extractor.py", line 66, in _fetch_mesh_data
    raise RuntimeError("Error while requesting data from server.")
RuntimeError: Error while requesting data from server.

### 📝 Steps to reproduce

I use python 3.9.11.
I use Fluent v23R1.
I use pyFluent 0.12.dev3.
I use visualisation & parametric packages 0.6.dev0.

I am not able to run the example from github, located here https://github.com/pyansys/pyfluent-visualization/blob/main/examples/00-postprocessing/post_processing_exhaust_manifold.py

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
aiohttp==3.8.3
aiosignal==1.2.0
ansys-api-fluent==0.3.4
ansys-api-platform-instancemanagement==1.0.0b3
-e git+https://github.com/pyansys/pyfluent.git@a3a23a3bb87a2f217759c948f260ce39ea0641a2#egg=ansys_fluent_core
-e git+https://github.com/pyansys/pyfluent-visualization.git@fbd0e9591295b8946aa22a808345d581ff059cc8#egg=ansys_fluent_visualization
ansys-platform-instancemanagement==1.0.2
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.1.0
async-timeout==4.0.2
attrs==22.1.0
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
colorama==0.4.6
contourpy==1.0.6
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.38.0
frozenlist==1.3.1
googleapis-common-protos==1.56.4
grpcio==1.50.0
h5py==3.7.0
idna==3.4
imageio==2.22.3
importlib-metadata==5.0.0
ipycanvas==0.13.1
ipyevents==2.0.1
ipykernel==6.17.0
ipython==8.6.0
ipython-genutils==0.2.0
ipyvtklink==0.2.3
ipywidgets==7.7.2
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.17.0
jupyter-server==1.21.0
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==1.1.1
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.6.2
matplotlib-inline==0.1.6
mistune==2.0.4
multidict==6.0.2
nbclassic==0.4.8
nbclient==0.7.0
nbconvert==7.2.3
nbformat==5.7.0
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.4
packaging==21.3
pandas==1.5.1
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.3.0
pooch==1.6.0
prometheus-client==0.15.0
prompt-toolkit==3.0.31
protobuf==3.20.2
protoc-gen-swagger==0.1.0
psutil==5.9.3
pure-eval==0.2.2
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pyrsistent==0.19.2
PySide6==6.4.0.1
PySide6-Addons==6.4.0.1
PySide6-Essentials==6.4.0.1
python-dateutil==2.8.2
pytz==2022.6
pyvista==0.37.0
pyvistaqt==0.9.0
pywin32==304
pywinpty==2.0.9
pyzmq==24.0.1
QtPy==2.2.1
requests==2.28.1
scooby==0.7.0
Send2Trash==1.8.0
shiboken6==6.4.0.1
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.0
terminado==0.17.0
tinycss2==1.2.1
tornado==6.2
traitlets==5.5.0
urllib3==1.26.12
vtk==9.2.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
widgetsnbextension==3.6.1
wslink==1.9.1
yarl==1.8.1
zipp==3.10.0
```

**Comment by seanpearsonuk** [comment]
Hi @ajain-work, please could you reach out to Achilleas Krikas (Ansys internal) regarding this issue.  This is a blocking issue for him. Many thanks in advance.

**Comment by ajain-work** [comment]
@achilleas-kr please try with pyfluent  ( 0.12.dev5) and visualization (0.6.dev2).

**Comment by achilleas-kr** [comment]
Hi @ajain-work, I got a different error now. Please see below:

(pyenv) C:\Users\akrikas\UnSync\PyAnsys\Learning>python post_processing_exhaust_manifold.py
Traceback (most recent call last):
  File "C:\Users\akrikas\UnSync\PyAnsys\Learning\post_processing_exhaust_manifold.py", line 227, in <module>
    xy_plot.plot("window-9")
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\matplot_objects.py", line 107, in plot
    matplot_windows_manager.plot(self, window_id)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\matplot_windows_manager.py", line 276, in plot
    window.plot()
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\matplot_windows_manager.py", line 98, in plot
    plot()
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\matplot_windows_manager.py", line 139, in __call__
    self.plotter.set_properties(properties)
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\plotter_defns.py", line 135, in set_properties
    self._reset()
  File "C:\Users\akrikas\pyfluent-visualization\src\ansys\fluent\visualization\matplotlib\plotter_defns.py", line 154, in _reset
    self.fig.canvas.set_window_title("PyFluent [" + self._window_id + "]")
AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title'

Let me know please for any advice. Thank you.

Regards,

Achilleas
