### ISSUE TITLE
Bug located in launcher.py

### ISSUE THREAD

**Issue by RebelYoung** [pyansys/pyfluent#1268]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When did I installed pyfluent : 2023.1.13 `version 0.12.1` in `venv py38`
When I launch the fluent 2022R2 by `launch_fluent` command in **python file (*.py)** both `PyCharm 2021.1` and` VScode`, there is an KeyError named "AWP_ROOT231".
**However, there is no problem in jupyter notebook.**

I created a new `venv` named `py38f11` and `pip install ansys.fluent.core==0.11.0`.
![contrast between different versions](https://user-images.githubusercontent.com/59256512/212532491-b4c34558-49f9-450e-aebf-a30ae3a74299.png)
`0.11.0` created a `solver` successfully.

I have read the lastest code in the launcher.py
There are some differences in the python file.
I can not debug in the code.
Can you check the issue in the lastest release ?

### 📝 Steps to reproduce

1. In PyCharm and VS code, program break up in a **python file** and print in console :
```python
Traceback (most recent call last):
  File "D:\pycharm\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm Community Edition 2021.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/young/code/a.py", line 4, in <module>
    solver = pyfluent.launch_fluent(mode="solver",show_gui=True)
  File "C:\Users\Admin\miniconda3\envs\py38\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 572, in launch_fluent
    launch_string = _generate_launch_string(
  File "C:\Users\Admin\miniconda3\envs\py38\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 414, in _generate_launch_string
    exe_path = _get_fluent_exe_path(**argvals)
  File "C:\Users\Admin\miniconda3\envs\py38\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 142, in _get_fluent_exe_path
    return get_exe_path()
  File "C:\Users\Admin\miniconda3\envs\py38\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 127, in get_exe_path
    exe_path = get_fluent_path()
  File "C:\Users\Admin\miniconda3\envs\py38\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 121, in get_fluent_path
    path = os.environ["AWP_ROOT" + "".join(FLUENT_VERSION.split("."))[:-1]]
  File "C:\Users\Admin\miniconda3\envs\py38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWP_ROOT231'
python-BaseException
```
I debugged the program.
When running into `class FluentVersion(Enum)` ,the variable of `FluentVersion` is '23.1.0' by default forever.
There is no 2023 version and no PATH named as `AWP_ROOT231`,so the program should change the `FluentVersion` into `AWP_ROOT222` automatically.

And I found some differences in `launcher.py` file.
I tried to change the default value of `FLUENT_VERSION` into `'22.2.0'`.
It doesn't work.

**in past file:**
```python
_THIS_DIR = os.path.dirname(__file__)
_OPTIONS_FILE = os.path.join(_THIS_DIR, "fluent_launcher_options.json")
FLUENT_VERSION = ["22.2"]
PIM_FLUENT_PRODUCT_VERSION = [FLUENT_VERSION[0].replace(".", "")]
FLUENT_EXE_PATH = []


class FluentVersion(Enum):
    """Contains the standard Ansys Fluent release."""

    version_22R2 = "22.2"
    version_23R1 = "23.1"
``` 
**in the lastest file:**
```python
_THIS_DIR = os.path.dirname(__file__)
_OPTIONS_FILE = os.path.join(_THIS_DIR, "fluent_launcher_options.json")
FLUENT_VERSION = "23.1.0"
_FLUENT_EXE_PATH = ""


class FluentVersion(Enum):
    """Contains the standard Ansys Fluent release."""

    version_22R2 = "22.2.0"
    version_23R1 = "23.1.0"
    version_23R2 = "23.2.0"
```

Strangely, there is no problem in the jupyter notebook as above.

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.5
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.12.1
ansys-fluent-parametric==0.6.0
ansys-fluent-visualization==0.6.0
ansys-platform-instancemanagement==1.0.2
appdirs==1.4.4
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
charset-normalizer==3.0.1
colorama @ file:///C:/b/abs_a9ozq0l032/croot/colorama_1672387194846/work
comm @ file:///C:/b/abs_1419earm7u/croot/comm_1671231131638/work
contourpy==1.0.6
cycler==0.11.0
debugpy @ file:///C:/ci/debugpy_1637073815078/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
entrypoints @ file:///C:/ci/entrypoints_1649926621247/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fonttools==4.38.0
googleapis-common-protos==1.58.0
grpcio==1.51.1
h5py==3.7.0
idna==3.4
imageio==2.24.0
importlib-metadata==6.0.0
ipykernel @ file:///C:/b/abs_b4f07tbsyd/croot/ipykernel_1672767104060/work
ipython @ file:///C:/b/abs_536xsn7rj0/croot/ipython_1670919360443/work
jedi @ file:///C:/ci/jedi_1644315425835/work
jupyter_client @ file:///C:/b/abs_b9pns5mx5p/croot/jupyter_client_1671703062216/work
jupyter_core @ file:///C:/b/abs_84df679bho/croot/jupyter_core_1672332237650/work
kiwisolver==1.4.4
matplotlib==3.6.3
matplotlib-inline @ file:///C:/ci/matplotlib-inline_1661934035815/work
nest-asyncio @ file:///C:/b/abs_3a_4jsjlqu/croot/nest-asyncio_1672387322800/work
numpy==1.24.1
packaging==23.0
pandas==1.5.2
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.4.0
platformdirs @ file:///C:/b/abs_73cc5cz_1u/croots/recipe/platformdirs_1662711386458/work
pointwise-glyph-client==2.0.10
pooch==1.6.0
prompt-toolkit @ file:///C:/b/abs_6coz5_9f2s/croot/prompt-toolkit_1672387908312/work
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil @ file:///C:/Windows/Temp/abs_b2c2fd7f-9fd5-4756-95ea-8aed74d0039flsd9qufz/croots/recipe/psutil_1656431277748/work
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
pyparsing==3.0.9
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz==2022.7
pyvista==0.37.0
pyvistaqt==0.9.0
pywin32==305.1
pyzmq @ file:///C:/ci/pyzmq_1657616005830/work
QtPy==2.3.0
requests==2.28.2
scooby==0.7.0
shiboken6==6.4.2
six @ file:///tmp/build/80754af9/six_1644875935023/work
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
tornado @ file:///C:/ci/tornado_1662476991259/work
traitlets @ file:///C:/b/abs_e5m_xjjl94/croot/traitlets_1671143896266/work
urllib3==1.26.14
vtk==9.2.5
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
wincertstore==0.2
zipp==3.11.0
```

**Comment by mkundu1** [comment]
The default Fluent version for PyFluent 0.12 is 23.1. Fluent 22.2 version can be launched by passing the `product_version` argument to `launch_fluent`.
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent(product_version="22.2.0")
```

**Comment by RebelYoung** [comment]
> The default Fluent version for PyFluent 0.12 is 23.1. Fluent 22.2 version can be launched by passing the `product_version` argument to `launch_fluent`.
> ```
> import ansys.fluent.core as pyfluent
> solver = pyfluent.launch_fluent(product_version="22.2.0")
> ```

Does It mean `pyfluent` can not choose the  `22.2.0` automatically when I just installed `2022R2` ？

**Comment by mkundu1** [comment]
@RebelYoung This will be fixed in the linked PR. Following is the order in which Fluent exe will be searched:

1. `PYFLUENT_FLUENT_ROOT` environment variable
2. `product_version` parameter passed with `launch_fluent`
3. value set by `set_fluent_exe_path`
4. value set by `set_ansys_version`
5. latest `AWP_ROOTXXX` environment variable - this one is automatic if Fluent is installed

**Comment by RebelYoung** [comment]
> The default Fluent version for PyFluent 0.12 is 23.1. Fluent 22.2 version can be launched by passing the `product_version` argument to `launch_fluent`.
> 
> ```
> import ansys.fluent.core as pyfluent
> solver = pyfluent.launch_fluent(product_version="22.2.0")
> ```

OK, I did tried this argument on last time, but it didn't work.
And, I tested again. It is successful.
