### ISSUE TITLE
Cannot launch pyaedt from within Fluent python commands

### ISSUE THREAD

**Issue by AdamTheEngineer-dev** [pyansys/pyfluent#1387]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

@hpohekar
If I try to launch Maxwell from within Fluent via pyaedt:

(%py-exec "import pyaedt")
(%py-exec "pyaedt.Maxwell3d()")

I get a module load error:

pyaedt INFO: using existing logger.
Traceback (most recent call last):
  File "<scheme>", line 1, in <module>
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\generic\design_types.py", line 233, in Maxwell3d
    aedt_process_id=aedt_process_id,
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\maxwell.py", line 2083, in __init__
    aedt_process_id,
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\application\Analysis3D.py", line 102, in __init__
    aedt_process_id,
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\application\Analysis.py", line 125, in __init__
    aedt_process_id,
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\application\Design.py", line 199, in __init__
    aedt_process_id,
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\desktop.py", line 418, in __init__
    self._init_cpython_new(non_graphical, new_desktop_session, version, self._main.student_version)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\PyAedt_2023R1\Lib\site-packages\pyaedt\desktop.py", line 719, in _init_cpython_new
    import ScriptEnv
  File "C:\Program Files\AnsysEM\v231\Win64\PythonFiles\DesktopPlugin\ScriptEnv.py", line 16, in <module>
    import PyDesktopPlugin
  File "C:\Program Files\AnsysEM\v231\Win64\PythonFiles\DesktopPlugin\PyDesktopPlugin.py", line 6, in <module>
    import PyDesktopPluginDll as AedtAPI
  File "C:\Program Files\AnsysEM\v231\Win64\PythonFiles\DesktopPlugin\PyDesktopPluginDll.py", line 32, in <module>
    AedtAPI = PyDLL(AedtAPIDll_file)
  File "C:\PROGRA~1\ANSYSI~1\v231\commonfiles\CPython\3_7\winx64\Release\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

PyDesktopPlugin.dll requires a dll but the path causes a problem.
The element in the path that seems to be an issue is:

C:\Program Files\ANSYS Inc\v231\fluent\ntbin\win64

So there seems to be a clash of DLL versions between what PyFluent needs and what PyAEDT needs.

### 📝 Steps to reproduce

In a venv that has pyaedt installed,
Run Fluent from command line.
In the TUI,run:
(%py-exec "import pyaedt")
(%py-exec "pyaedt.Maxwell3d()")

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R1

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
appdirs==1.4.4
backcall==0.2.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
clr-loader==0.2.5
colorama==0.4.6
cycler==0.11.0
decorator==5.1.1
fonttools==4.38.0
h5py==3.7.0
idna==3.4
imageio==2.24.0
ipython==7.34.0
jedi==0.18.2
kiwisolver==1.4.4
matplotlib==3.5.3
matplotlib-inline==0.1.6
numpy==1.21.6
packaging==23.0
pandas==1.3.5
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
plumbum==1.8.1
pooch==1.6.0
prompt-toolkit==3.0.37
psutil==5.9.4
pyaedt==0.6.47
pycparser==2.21
Pygments==2.14.0
pyparsing==3.0.9
python-dateutil==2.8.2
pythonnet==3.0.1
pytz==2022.7.1
pyvista==0.37.0
pywin32==305
requests==2.28.2
rpyc==5.3.0
scooby==0.7.0
six==1.16.0
traitlets==5.9.0
typing_extensions==4.4.0
urllib3==1.26.14
vtk==9.2.5
wcwidth==0.2.6
```

**Comment by mkundu1** [comment]
Should be a Fluent side issue

**Comment by dnwillia-work** [comment]
Yes, agree,  It's not a bug in the PyFluent library.
