### ISSUE TITLE
boundary_conditions.<boundary_condition_type>.create

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#583]
Is there a use case for this method, which is available? Using it leads to various errors.

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk I am seeing this error:
> 
> ```
> >>> r.setup.boundary_conditions.velocity_inlet.create('i1')
> Error: api-create-obj: new objects of this type cannot be created
> Error Object: "setup/boundary-conditions/velocity-inlet"
> 2022-07-03 16:52:47,247 root         ERROR    GRPC_ERROR: api-create-obj: new objects of this type cannot be created
> Error Object: setup/boundary-conditions/velocity-inlet
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "e:\ansysdev\v195\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 520, in create
>     self.flproxy.create(self.path, name)
>   File "e:\ansysdev\v195\pyfluent\src\ansys\fluent\core\services\settings.py", line 86, in _fn
>     return fn(self, *args, **kwds)
>   File "e:\ansysdev\v195\pyfluent\src\ansys\fluent\core\services\settings.py", line 172, in create
>     self.__service_impl.create(request)
>   File "e:\ansysdev\v195\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 18, in func
>     raise RuntimeError(ex.details()) from None
> RuntimeError: api-create-obj: new objects of this type cannot be created
> Error Object: setup/boundary-conditions/velocity-inlet
> ```

@h-krishnan running 23R1 I see the same as you have reported above. 

So, we shall do this as client-side fix such that the name object container does not 
have a create method if user-creatable? is False, right?  Adding to roadmap.

**Comment by seanpearsonuk** [comment]
I will re-check current behaviour

**Comment by seanpearsonuk** [comment]
ADO bug 704554
