### ISSUE TITLE
Want to evaluate a named expression

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#638]
Fluent is initialized (and solved). I am able to evaluate parameter_4 in Fluent via the named expressions panel; parameter_1 is just a constant so that one can also be evaluated. I wanted to do the evaluations also in PyFluent. But I cannot find an evaluation method under the `named_expressions` object. There is a `values` method under the named_expressions container that returns a dict_values object with the right number of elements.  Going to figure out how it might be used. But meanwhile seems that there is no straightforward way to evaluate.

I also called `unit` on the expression to see if it would return the resultant units of the expression. I don't know why that should trigger an exception for each expression. Unit is not active, which doesn't seem right. The help for unit doesn't seem to specify what the method is for. 

@h-krishnan On a separate question, should we have a get_resolved_state method in the settings objects? That could be done either client or server side. Currently unresolvable settings could be NaN for example.

```
>>> s.solver.root.setup.named_expressions["parameter_1"]()
{'name': 'parameter_1', 'definition': '1 [m/s]', 'description': '', 'input_parameter': False, 'output_parameter': False}
>>> s.solver.root.setup.named_expressions["parameter_4"]()
{'definition': "AreaAve(VelocityMagnitude,['pressure-outlet-7'])", 'description': '', 'output_parameter': False}
>>>
>>>
>>> dir(s.solver.root.setup.named_expressions["parameter_4"])
['__call__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_flproxy', '_is_protocol', '_name', '_parent', '_print_state_helper', '_setattr', '_state_type', 'child_names', 'command_names', 'definition', 'description', 'flproxy', 'fluent_name', 'get_active_child_names', 'get_active_command_names', 'get_active_query_names', 'get_attr', 'get_attrs', 'get_name', 'get_state', 'input_parameter', 'is_active', 'name', 'obj_name', 'output_parameter', 'parameterid', 'parametername', 'parent', 'path', 'print_state', 'query_names', 'rename', 'set_flproxy', 'set_state', 'to_python_keys', 'to_scheme_keys', 'unit']
>>> s.solver.root.setup.named_expressions["parameter_4"].unit
<ansys.fluent.core.solver.flobject.unit object at 0x000001B19A443A30>
>>> s.solver.root.setup.named_expressions["parameter_4"].unit()

Error: api-get-var: the object is not active
Error Object: "setup/named-expressions/parameter_4/unit"
2022-07-15 12:22:26,647 root         ERROR    GRPC_ERROR: api-get-var: the object is not active
Error Object: setup/named-expressions/parameter_4/unit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 195, in __call__
    return self.get_state()
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 199, in get_state
    return self.to_python_keys(self.flproxy.get_var(self.path))
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\settings.py", line 154, in get_var
    response = self.__service_impl.get_var(request)
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\error_handler.py", line 18, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: api-get-var: the object is not active
Error Object: setup/named-expressions/parameter_4/unit
>>> s.solver.root.setup.named_expressions["parameter_4"].unit
<ansys.fluent.core.solver.flobject.unit object at 0x000001B19A443A30>
>>> help(s.solver.root.setup.named_expressions["parameter_4"].unit)
Help on unit in module ansys.fluent.core.solver.flobject object:
class unit(String)
 |  unit(*args, **kwds)
 |
 |  'unit' child.
 |
 |  Method resolution order:
 |      unit
 |      String
 |      SettingsBase
 |      Base
 |      typing.Generic
 |      builtins.object
 |
 |  Data and other attributes defined here:
 |
 |  __parameters__ = ()
 |
 |  fluent_name = 'unit'
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from String:
 |
 |  __orig_bases__ = (ansys.fluent.core.solver.flobject.SettingsBase[str],...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from SettingsBase:
 |
 |  __call__(self) -> ~StateT
 |      Alias for self.get_state.
 |
 |  get_state(self) -> ~StateT
 |      Get the state of this object.
 |
 |  print_state(self, out=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, indent_factor=2)
 |      Print the state of this object.
 |
 |  set_state(self, state: ~StateT)
 |      Set the state of this object.
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from SettingsBase:
 |
 |  to_python_keys(value: ~StateT) -> ~StateT from builtins.type
 |      Convert value to have keys with python names.
 |
 |      This is overridden in Group, NamedObject and ListObject classes.
 |
 |  to_scheme_keys(value: ~StateT) -> ~StateT from builtins.type
 |      Convert value to have keys with scheme names.
 |
 |      This is overridden in Group, NamedObject and ListObject classes.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from Base:
 |
 |  __init__(self, name: str = None, parent=None)
 |      __init__ of Base class.
 |
 |  __setattr__(self, name, value)
 |      Implement setattr(self, name, value).
 |
 |  get_attr(self, attr) -> Any
 |      Get the requested attribute for the object.
 |
 |  get_attrs(self, attrs) -> Any
 |      Get the requested attributes for the object.
 |
 |  is_active(self) -> bool
 |      Indicates if the object is active.
 |
 |  set_flproxy(self, flproxy)
 |      Set flproxy object.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from Base:
 |
 |  flproxy
 |      Proxy object.
 |
 |      This is set at the root level, and accessed via parent for child
 |      classes.
 |
 |  obj_name
 |      Scheme name of this object.
 |
 |      By default, this returns the object's static name. If the object
 |      is a named-object child, the object's name is returned.
 |
 |  parent
 |      The parent (container) object.
 |
 |  path
 |      Path of this object.
 |
 |      Constructed from obj_name of self and path of parent.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from Base:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from typing.Generic:
 |
 |  __class_getitem__(params) from builtins.type
 |
 |  __init_subclass__(*args, **kwargs) from builtins.type
 |      This method is called when a class is subclassed.
 |
 |      The default implementation does nothing. It may be
 |      overridden to extend subclasses.
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from typing.Generic:
 |
 |  __new__(cls, *args, **kwds)
 |      Create and return a new object.  See help(type) for accurate signature.
>>>
>>> dir(s.solver.root.setup.named_expressions["parameter_4"])
['__call__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_flproxy', '_is_protocol', '_name', '_parent', '_print_state_helper', '_setattr', '_state_type', 'child_names', 'command_names', 'definition', 'description', 'flproxy', 'fluent_name', 'get_active_child_names', 'get_active_command_names', 'get_active_query_names', 'get_attr', 'get_attrs', 'get_name', 'get_state', 'input_parameter', 'is_active', 'name', 'obj_name', 'output_parameter', 'parameterid', 'parametername', 'parent', 'path', 'print_state', 'query_names', 'rename', 'set_flproxy', 'set_state', 'to_python_keys', 'to_scheme_keys', 'unit']
>>>
>>> s.solver.root.setup.named_expressions["parameter_4"]()
{'definition': "AreaAve(VelocityMagnitude,['pressure-outlet-7'])", 'description': '', 'output_parameter': False}
>>> s.solver.root.setup.named_expressions["parameter_1"].unit()
Error: api-get-var: the object is not active
Error Object: "setup/named-expressions/parameter_1/unit"
2022-07-15 12:26:12,007 root         ERROR    GRPC_ERROR: api-get-var: the object is not active
Error Object: setup/named-expressions/parameter_1/unit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 195, in __call__
    return self.get_state()
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 199, in get_state
    return self.to_python_keys(self.flproxy.get_var(self.path))
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\settings.py", line 154, in get_var
    response = self.__service_impl.get_var(request)
  File "E:\ANSYSDev\pyfluent10\.venv\lib\site-packages\ansys\fluent\core\services\error_handler.py", line 18, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: api-get-var: the object is not active
Error Object: setup/named-expressions/parameter_1/unit
```

**Comment by seanpearsonuk** [comment]
Completed in settings API
