### ISSUE TITLE
near wall treatment: inconsistent option naming

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#672]
With model = 'k-epsilon-standard' in 22R2
```
>>> s.solver.root.setup.models.viscous.near_wall_treatment.get_attr('allowed-values')
['standard-wall-*fn*', 'non-equilibrium-wall-*fn*', 'enhanced-wall-treatment', 'menter-lechner?', 'scalable-wall-*functions*', 'user-defined-wall-*functions*']
```

**Comment by seanpearsonuk** [comment]
Tried in 23R1 but hit other issues, that might be due to local set up. 

```
>>> s.solver.root.setup.models.viscous.near_wall_treatment.get_attr('allowed-values')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\spearson\AppData\Local\Programs\Python\Python38\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 145, in get_attr
    if attr != "active?" and attrs.get("active?", True) is False:
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by seanpearsonuk** [comment]
TODO: US
