### ISSUE TITLE
Inconsistent graphics object interactions through settings API

### ISSUE THREAD

**Issue by seanpearsonuk** [pyansys/pyfluent#751]
```
>>> s = pf.launch_fluent(mode="solver", show_gui=True)
```
- In Fluent: read the mixing elbow case and data; create any contour object

```
>>> s.results.graphics.contour['contour-1'].surfaces.allowed_values()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 195, in allowed_values
    return self.get_attr("allowed-values")
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 147, in get_attr
    raise RuntimeError("Object is not active")
RuntimeError: Object is not active
>>> s.results.graphics.contour['contour-1'].surfaces()
Error: api-get-var: the object is not active
Error Object: "results/graphics/contour/contour-1/surfaces"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 230, in __call__
    return self.get_state()
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 234, in get_state
    return self.to_python_keys(self.flproxy.get_var(self.path))
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\services\settings.py", line 86, in _fn
    return fn(self, *args, **kwds)
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\services\settings.py", line 154, in get_var
    response = self.__service_impl.get_var(request)
  File "e:\ansysdev\pyfluent16\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: api-get-var: the object is not active
Error Object: results/graphics/contour/contour-1/surfaces
>>> s.results.graphics.contour['contour-1']()
{'name': 'contour-1', 'field': 'pressure', 'filled': True, 'boundary_values': True, 'contour_lines': False, 'node_values': True, 'surfaces_list': ['cold-inlet', 'hot-inlet', 'outlet', 'symmetry-xyplane', 'wall-inlet'], 'range_option': {'option': 'auto-range-on', 'auto_range_on': {'global_range': True}}, 'coloring': {'option': 'smooth', 'smooth': False}, 'color_map': {'visible': True, 'size': 100, 'color': 'field-velocity', 'log_scale': False, 'format': '%0.2e', 'user_skip': 9, 'show_all': True, 'position': 1, 'font_name': 'Helvetica', 'font_automatic': True, 'font_size': 0.032, 'length': 0.54, 'width': 6.0}, 'display_state_name': 'None'}
>>> s.results.graphics.contour['contour-1'].surfaces.is_active()
False
>>> s.results.graphics.contour['contour-1'].is_active()
True
>>> s.results.graphics.contour['contour-1'].field.is_active()
True
```

- The contour state is fully queryable. Any attempt to get specific information about its surfaces child leads to errors due to is-active being false.

**Comment by seanpearsonuk** [comment]
It's surface_list rather than surfaces.
