### ISSUE TITLE
failed license check

### ISSUE THREAD

**Issue by g-pagliuca** [pyansys/pyfluent#880]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Somehow I cannot grab a license, this is the error message I get from the fluent GUI:

```
ANSYS LICENSE MANAGER ERROR:Request name cfd_solve_level2 does not exist in the licensing pool.
License server machine is down or not responding.
 See the system administrator about starting the license server system, or
 make sure you're referring to the right host (see LM_LICENSE_FILE).
Feature:       cfd_solve_level2
Hostname:      license.example.com
License path:  1055@license.example.com:
FlexNet Licensing error:-96,7
```

I do have a valid license since I can run fluent launching it from the terminal

This one below is the output from ipython:

```
2022-09-14 11:39:57,357 root         INFO     Launching Fluent with cmd: /glb/apps/hpc/EasyBuild/software/rhel/7/ANSYS/2022R2/v222/fluent/bin/fluent 3ddp -driver opengl -sifile="/tmp/serverinfo-k4d166wc.txt" -nm
2022-09-14 11:39:58,364 root         INFO     Waiting for Fluent to launch...19 seconds remaining
2022-09-14 11:39:59,366 root         INFO     Waiting for Fluent to launch...18 seconds remaining
2022-09-14 11:40:00,368 root         INFO     Waiting for Fluent to launch...17 seconds remaining
2022-09-14 11:40:01,371 root         INFO     Waiting for Fluent to launch...16 seconds remaining
2022-09-14 11:40:02,373 root         INFO     Waiting for Fluent to launch...15 seconds remaining
2022-09-14 11:40:03,376 root         INFO     Waiting for Fluent to launch...14 seconds remaining
2022-09-14 11:40:04,379 root         INFO     Fluent process is successfully launched.
Exception ignored in: <finalize object at 0x2acaa2379020; dead>
Traceback (most recent call last):
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/site-packages/ansys/fluent/core/session.py", line 362, in _exit
    scheme_eval.exec(("(exit-server)",))
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/site-packages/ansys/fluent/core/services/scheme_eval.py", line 224, in exec
    response = self.service.exec(request)
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/site-packages/ansys/fluent/core/services/scheme_eval.py", line 47, in exec
    return self.__stub.Exec(request, metadata=self.__metadata)
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/glb/data/nl_ffre_base/nlgpaf/miniconda3/envs/wh/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1663148430.825629166","description":"Error received from peer ipv4:145.26.81.166:8080","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"Socket closed","grpc_status":14}"
```

### 📝 Steps to reproduce

Launch fluent

### 💻 Which operating system are you using?

Linux

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
aiohttp==3.8.1
aiosignal==1.2.0
ansys-api-fluent==0.3.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.10.1
ansys-fluent-parametric==0.4.1
ansys-fluent-visualization==0.4.1
ansys-platform-instancemanagement==1.0.2
anyio @ file:///tmp/build/80754af9/anyio_1644481695334/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///tmp/build/80754af9/argon2-cffi-bindings_1644553347904/work
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
async-timeout==4.0.2
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///opt/conda/conda-bld/beautifulsoup4_1650462163268/work
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
Bottleneck @ file:///opt/conda/conda-bld/bottleneck_1657175564434/work
brotlipy==0.7.0
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
cffi @ file:///tmp/abs_98z5h56wf8/croots/recipe/cffi_1659598650955/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
cryptography @ file:///tmp/build/80754af9/cryptography_1652101588599/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython @ file:///opt/conda/conda-bld/cython_1656941947712/work
debugpy @ file:///home/builder/ci_310/debugpy_1640789504635/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
entrypoints @ file:///tmp/build/80754af9/entrypoints_1649908313000/work
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fastjsonschema @ file:///opt/conda/conda-bld/python-fastjsonschema_1661371079312/work
fonttools==4.25.0
frozenlist==1.3.1
googleapis-common-protos==1.56.4
grpcio==1.47.0
gssapi==1.8.1
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imageio==2.21.2
importlib-metadata==4.12.0
ipycanvas==0.13.0
ipyevents==2.0.1
ipykernel @ file:///opt/conda/conda-bld/ipykernel_1662361798230/work
ipython @ file:///opt/conda/conda-bld/ipython_1657652213665/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipyvtklink==0.2.2
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
jedi @ file:///tmp/build/80754af9/jedi_1644315229345/work
Jinja2 @ file:///opt/conda/conda-bld/jinja2_1647436528585/work
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1650007830677/work
jupyter @ file:///tmp/abs_33h4eoipez/croots/recipe/jupyter_1659349046347/work
jupyter-console @ file:///opt/conda/conda-bld/jupyter_console_1647002188872/work
jupyter-core @ file:///opt/conda/conda-bld/jupyter_core_1651671229925/work
jupyter-server @ file:///tmp/abs_b88b31b8-83b9-476d-a46d-e563c421f38fvsnyi1ur/croots/recipe/jupyter_server_1658754481507/work
jupyter_client @ file:///opt/conda/conda-bld/jupyter_client_1662504365333/work
jupyterlab @ file:///tmp/abs_12f3h01vmy/croots/recipe/jupyterlab_1658907535764/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///opt/conda/conda-bld/jupyterlab_server_1650462180599/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
kiwisolver @ file:///opt/conda/conda-bld/kiwisolver_1653292039266/work
krb5==0.4.0
MarkupSafe @ file:///opt/conda/conda-bld/markupsafe_1654597864307/work
matplotlib @ file:///opt/conda/conda-bld/matplotlib-suite_1660167928326/work
matplotlib-inline @ file:///opt/conda/conda-bld/matplotlib-inline_1662014470464/work
mistune @ file:///home/builder/ci_310/mistune_1640791641754/work
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
multidict==6.0.2
munkres==1.1.4
nbclassic @ file:///opt/conda/conda-bld/nbclassic_1644943264176/work
nbclient @ file:///tmp/build/80754af9/nbclient_1650290238894/work
nbconvert @ file:///opt/conda/conda-bld/nbconvert_1649751911790/work
nbformat @ file:///tmp/build/80754af9/nbformat_1649844915018/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1649830051683/work
notebook @ file:///tmp/abs_abf6xa6h6f/croots/recipe/notebook_1659083654985/work
ntlm-auth==1.5.0
numexpr @ file:///opt/conda/conda-bld/numexpr_1656940300424/work
numpy @ file:///tmp/abs_653_j00fmm/croots/recipe/numpy_and_numpy_base_1659432701727/work
osisoft.pidevclub.piwebapi==1.1.4
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.4.3
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.2.0
Pint @ file:///home/conda/feedstock_root/build_artifacts/pint_1650914444525/work
ply==3.11
prometheus-client @ file:///tmp/abs_d3zeliano1/croots/recipe/prometheus_client_1659455100375/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.20.1
protoc-gen-swagger==0.1.0
psutil @ file:///opt/conda/conda-bld/psutil_1656431268089/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing @ file:///opt/conda/conda-bld/pyparsing_1661452539315/work
PyQt5-sip==12.11.0
pyrsistent @ file:///home/builder/ci_310/pyrsistent_1640807196327/work
PySide6==6.2.4
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
pyspnego==0.6.0
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz @ file:///opt/conda/conda-bld/pytz_1654762638606/work
pyvista==0.36.1
pyvistaqt==0.9.0
pyzmq @ file:///opt/conda/conda-bld/pyzmq_1657724186960/work
qtconsole @ file:///opt/conda/conda-bld/qtconsole_1662018252641/work
QtPy @ file:///opt/conda/conda-bld/qtpy_1662014892439/work
requests @ file:///opt/conda/conda-bld/requests_1657734628632/work
requests-kerberos==0.14.0
requests-ntlm==1.1.0
scooby==0.6.0
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
shiboken6==6.2.4
sip @ file:///tmp/abs_44cd77b_pu/croots/recipe/sip_1659012365470/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio @ file:///home/builder/ci_310/sniffio_1640794799774/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
terminado @ file:///tmp/build/80754af9/terminado_1644322583911/work
testpath @ file:///opt/conda/conda-bld/testpath_1655908557405/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tornado @ file:///opt/conda/conda-bld/tornado_1662061693373/work
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
typing_extensions @ file:///tmp/abs_ben9emwtky/croots/recipe/typing_extensions_1659638822008/work
urllib3 @ file:///tmp/abs_5dhwnz6atv/croots/recipe/urllib3_1659110457909/work
vtk==9.2.0rc2
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client @ file:///home/builder/ci_310/websocket-client_1640795866898/work
widgetsnbextension @ file:///tmp/build/80754af9/widgetsnbextension_1645009354667/work
wslink==1.8.2
xarray @ file:///opt/conda/conda-bld/xarray_1639166117697/work
xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work
yarl==1.8.1
zipp==3.8.1
```

**Comment by seanpearsonuk** [comment]
@g-pagliuca please could you specify how you are calling `launch_fluent`.  Thanks.

**Comment by seanpearsonuk** [comment]
@g-pagliuca please can you can verify that the licensing environment variables are the same when you are launching Fluent from PyFluent.

**Comment by g-pagliuca** [comment]
Sorry I forgot to close this, my IT helped in setting up correctly the license env variable
